name = "scorebox-live"
main = "worker.js"
compatibility_date = "2026-09-25"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "scorebox_live"
database_name = "scorebox-live"
database_id = "059c9f83-f2ff-46c5-a900-c00711331f60"